name: Run Unit Test

on:

  push:
    branches: [ pokedex_jetpack_compose ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run UnitTestCoverage debug
        id: tests
        run: ./gradlew testDebugUnitTestCoverage

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/jacoco/testDebugUnitTestCoverage/html/index.html

      - name: Build with Gradle
        id: build
        run: ./gradlew assembleDebug